dubbo:
  application:
    name: stuService
    registry: zookeeper://192.168.126.128:2181
  protocol:
    port: 20881
spring:
  datasource:
    url: jdbc:mysql:///classroom
    username: root
    password: 123
    driver-class-name: com.mysql.jdbc.Driver
server:
  port: 8081
